name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! After you submit this issue, check this GitHub thread for any updates/responses from the Eureka! team.
  - type: checkboxes
    id: terms
    attributes:
      label: FAQ check
      description: Before continuing, have you checked to see if your question has been answered in our [Frequently Asked Questions](https://eurekadocs.readthedocs.io/en/latest/faq.html)?
      options:
        - label: Yes, I checked the FAQ and my question has not been addressed.
          required: true
  - type: dropdown
    id: instrument
    attributes:
      label: Instrument
      description: Which instrument or piece of code were you running?
      multiple: true
      options:
        - NIRISS (Stages 1-3)
        - NIRSpec (Stages 1-3)
        - NIRCam (Stages 1-3)
        - MIRI (Stages 1-3)
        - Light curve fitting (Stages 4-6)
        - Other (any stage)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error traceback output
      description: Please copy and paste the full traceback of the error you encountered.
  - type: input
    id: OS
    attributes:
      label: What operating system are you using?
      placeholder: E.g., Windows 11; Mac OS 10.10 El Capitan
  - type: input
    id: python_version
    attributes:
      label: What version of Python are you running?
      description: If you're not sure, open a terminal with the environment you're running Eureka! in and type "python --version"
      placeholder: E.g., Python 3.7
  - type: textarea
    id: package_list
    attributes:
      label: What Python packages do you have installed?
      description: To get a full list, open a terminal with the environment you're running Eureka! in and type "conda list". Paste the full output here.
  - type: checkboxes
    id: codeofconduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kevin218/Eureka/blob/main/code_of_conduct.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
